version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: saas_house_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: saashouse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: saas_pgadmin4
    environment:
      # Ini emel dan password untuk LOGIN ke dashboard pgAdmin nanti
      PGADMIN_DEFAULT_EMAIL: admin@saashouse.com
      PGADMIN_DEFAULT_PASSWORD: rootpassword
      # Penting: Supaya pgAdmin tak pening dengan permission di Docker
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: "10"
    ports:
      - "8081:80"
    depends_on:
      - postgres
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: saas_house_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data: