TRUNCATE TABLE projects CASCADE;
TRUNCATE TABLE subscriptions CASCADE;
TRUNCATE TABLE invoices CASCADE;
TRUNCATE TABLE payments CASCADE;
TRUNCATE TABLE requests CASCADE;
TRUNCATE TABLE request_comments CASCADE;
